### ISSUE TITLE
Ajout de l'option Restore backup

### ISSUE THREAD

**Issue by vinceg77** [NextDom/NextDom_Installer#1]
Ajouter une option à l'outil qui permettrait de restaurer un backup suite à l'installation de la branche...

Par exemple on pourrait faire :

 .\NextDom_Installer_v1.5.sh -gitbr tabranche -backup backup-MaisonChelles-0.6.0-RC2-2019-12-30-07-18-01.tar.gz
 ou
 .\NextDom_Installer_v1.5.sh -gitbr tabranche -backup /var/lib/nextdom/backup/backup-MaisonChelles-0.6.0-RC2-2019-12-30-07-18-01.tar.gz

**Comment by vinceg77** [comment]
Prems au fait  !!!!

**Comment by therealcorwin** [comment]
Demande prise en compte

**Comment by therealcorwin** [comment]
fonction dispo dans RC1 du script enjoy :D
