### ISSUE TITLE
Bug (a determiner)

### ISSUE THREAD

**Issue by vinceg77** [NextDom/NextDom_Installer#3]
![image](https://user-images.githubusercontent.com/51484329/71939505-36695080-31b3-11ea-8a41-95c8dadc0c3b.png)
??????

la branche Fix1627 existe pourtant bien :
![image](https://user-images.githubusercontent.com/51484329/71939493-218cbd00-31b3-11ea-991a-7b46d8e297b9.png)

**Comment by iWils** [comment]
@vinceg77 : As-tu fait un `git clone https://github.com/NextDom/NextDom_Installer.git` ?

**Comment by vinceg77** [comment]
Non j'ai fait comme toi la premiere fois ! un wget !
