### ISSUE TITLE
BUG execution V1.8 fresh install DEBIAN BUSTER

### ISSUE THREAD

**Issue by therealcorwin** [NextDom/NextDom_Installer#4]
Lors de l'exécution du script v1.8 sur une buster fraichement installée les messages d'erreurs suivants apparaissent au cours de l'installation : 

> ./NextDom_Installer_v1.8.sh: ligne 84 : [: == : opérateur unaire attendu
./NextDom_Installer_v1.8.sh: ligne 91 : [: == : opérateur unaire attendu
./NextDom_Installer_v1.8.sh: ligne 98 : [: == : opérateur unaire attendu

Cela stop l'installation

**Comment by vinceg77** [comment]
Qu'est ce que tu appelles "installation" ? 
C'est un script bash, il ne "s'installe" donc pas mais s'execute...

**Comment by vinceg77** [comment]
effectivement les changements de branches demandées par le script n’aboutissent pas et produisent des erreurs si avant le lancement du script il n'y avait pas d'installation valide de nextdom...

Les commandes suivantes par exemple (qui installent un deb de netxdom) lancées préalablement au script lui permettent ensuite de fonctionner correctement : 
```
sed -i '/non-free/!s/main/main non-free/' /etc/apt/sources.list
apt update && apt -y install ca-certificates wget && wget -O- https://raw.githubusercontent.com/NextDom/NextDom-DebInstaller/master/deb-install.sh | bash
```

**Comment by therealcorwin** [comment]
Normalement Corrigé dans la V2.0 Beta.
